### ISSUE TITLE
crash after opening a folder as project

### ISSUE THREAD

**Issue by c33s** [flathub/com.jetbrains.PhpStorm#95]
```
lWindowHeader$2). Use `ActionUpdateThread.BGT`.
[0115/033250.984145:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm abortingnow. You need to make sure that /app/extra/phpstorm/jbr/lib/chrome-sandbox is owned by root and has mode 4755.
```

updated (reinstalled) phpstorm flatpak todoay, it sadly still crashes with the error above

**Comment by c33s** [comment]
newbe question: is this package https://github.com/refi64/zypak required to fix this problem?

**Comment by c33s** [comment]
workaround for me is to downgrade to 2022.3.3
```
flatpak remote-info --log flathub com.jetbrains.PhpStorm
flatpak update --commit=acf67cd4d0f8b0fd8e0655a0e7eafdaaf6732cc96d24bad889f3865021cfa241 com.jetbrains.PhpStorm

```

**Comment by aliasbody** [comment]
Same issue here with the latest version 2023.3.3. Here is the log:

```
User Logs:
--fev 05 16:26:29 ryzenbox java[48599]: Failed to load module "canberra-gtk-module"
fev 05 16:26:29 ryzenbox java[48599]: Failed to load module "pk-gtk-module"
fev 05 16:26:29 ryzenbox java[48599]: Failed to load module "canberra-gtk-module"
fev 05 16:26:29 ryzenbox java[48599]: Failed to load module "pk-gtk-module"
fev 05 16:26:35 ryzenbox java[48790]: Failed to load module "canberra-gtk-module"
fev 05 16:26:35 ryzenbox java[48790]: Failed to load module "pk-gtk-module"
fev 05 16:26:35 ryzenbox java[48790]: Failed to load module "canberra-gtk-module"
fev 05 16:26:35 ryzenbox java[48790]: Failed to load module "pk-gtk-module"
fev 05 16:27:12 ryzenbox java[49051]: Failed to load module "canberra-gtk-module"
fev 05 16:27:12 ryzenbox java[49051]: Failed to load module "pk-gtk-module"
fev 05 16:27:12 ryzenbox java[49051]: Failed to load module "canberra-gtk-module"
fev 05 16:27:12 ryzenbox java[49051]: Failed to load module "pk-gtk-module"
fev 05 16:27:12 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:12,600 [    557]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.psi.search.FilenameIndex initializer requests com.intellij.ide.plugins.PluginUtil instance
fev 05 16:27:12 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:12,709 [    666]   WARN - #c.i.w.i.i.l.m.ModuleBridgeLoaderService - Loaded from cache, but no serialized modules found. Workspace model cache will be ignored, project structure will be recreated.
fev 05 16:27:12 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:12,919 [    876]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.lang.javascript.psi.jsdoc.impl.JSDocCustomTags initializer requests com.intellij.lang.javascript.JSDisposable instance
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:13,010 [    967]   WARN - #c.i.s.ComponentManagerImpl - org.zmlx.hg4idea.provider.HgChangeProvider initializer requests com.intellij.openapi.vcs.FileStatusFactory instance
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:13,394 [   1351]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.psi.LanguageSubstitutors initializer requests com.intellij.psi.LanguageSubstitutors instance
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:13,754 [   1711]   WARN - #c.i.o.a.i.ActionUpdater - 395 ms to grab EDT for ToolWindowHeader$2#Update@ToolwindowTitle (com.intellij.toolWindow.ToolWindowHeader$2)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:13,783 [   1740]   WARN - #c.i.o.a.i.ActionUpdater - 322 ms to grab EDT for ToolWindowHeader$2#Update@ToolwindowTitle (com.intellij.toolWindow.ToolWindowHeader$2)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:13,984 [   1941]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate com.jetbrains.php.tools.quality.psalm.PsalmSettingsTransferStartupActivity to ProjectActivity [Plugin: com.intellij.php.psalm]
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: com.intellij.diagnostic.PluginException: Migrate com.jetbrains.php.tools.quality.psalm.PsalmSettingsTransferStartupActivity to ProjectActivity [Plugin: com.intellij.php.psalm]
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:277)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:192)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:191)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:13,988 [   1945]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate com.jetbrains.php.tools.quality.phpstan.PhpStanSettingsTransferStartupActivity to ProjectActivity [Plugin: com.intellij.php.tools.quality.phpstan]
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: com.intellij.diagnostic.PluginException: Migrate com.jetbrains.php.tools.quality.phpstan.PhpStanSettingsTransferStartupActivity to ProjectActivity [Plugin: com.intellij.php.tools.quality.phpstan]
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:277)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:192)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:191)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
fev 05 16:27:13 ryzenbox com.jetbrains.PhpStorm.desktop[49051]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
fev 05 16:27:14 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:14,039 [   1996]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.database.console.session.DatabaseSessionManager initializer requests com.intellij.database.console.session.DatabaseSessionViewService instance
fev 05 16:27:14 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:14,070 [   2027]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 1 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-985749b364ce-JavaScript-PS-233.14015.96
fev 05 16:27:14 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:14,141 [   2098]   WARN - #c.i.o.v.n.p.d.e.DurableEnumeratorFactory - [enumerator.mmapped]: .valueToId map is out-of-sync with .valuesLog data -> rebuilding it
fev 05 16:27:33 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:33,979 [  21936]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 1 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-985749b364ce-JavaScript-PS-233.14015.96
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:34,125 [  22082]   WARN - #o.j.p.t.TextMateService - Cannot find referenced file `./language-configuration.json` in bundle `/app/extra/phpstorm/plugins/textmate/lib/bundles/mdx`
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:34,162 [  22119]   WARN - #o.j.p.t.TextMateService - Cannot find referenced file `./language-configuration.json` in bundle `/app/extra/phpstorm/plugins/textmate/lib/bundles/mdx`
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:34,257 [  22214]   WARN - #o.j.p.t.TextMateService - Cannot find referenced file `./language-configuration.json` in bundle `/app/extra/phpstorm/plugins/textmate/lib/bundles/mdx`
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:34,361 [  22318]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.psi.codeStyle.CodeStyleSettingsCustomizable initializer requests com.intellij.util.LocaleSensitiveApplicationCacheService instance
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:34,501 [  22458]   WARN - #c.i.s.ComponentManagerImpl - com.intellij.ui.jcef.JBCefApp$Holder initializer requests com.intellij.ui.jcef.JBCefAppCache instance
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: 2024-02-05 16:27:34,582 [  22539]   WARN - #c.i.o.a.i.ActionUpdater - 389 ms to grab EDT for ToolWindowHeader$2#GetChildren@ToolwindowTitle (com.intellij.toolWindow.ToolWindowHeader$2)
fev 05 16:27:34 ryzenbox com.jetbrains.PhpStorm.desktop[49051]: [0205/162734.660192:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/phpstorm/jbr/lib/chrome-sandbox is owned by root and has mode 4755.
--

```
